### ISSUE TITLE
7z - unknown archive exception

### ISSUE THREAD

**Issue by MrMikeJJ** [adoconnection/SevenZipExtractor#1]
Hi,
Thank you for the nuget package and wrapper :)
I have come across a little issue trying to open a 7z archive, it throws the exception 
7z is not a known archive type

If i rename the archive to .SevenZip it then works. So guess it's just a problem with detecting the type from the file extension ?

thanks
Mike

**Comment by adoconnection** [comment]
Hi Mike!
Thanks for report. Exactly. I'll fix it tomorrow

**Comment by adoconnection** [comment]
done, also new it turns out 7z supports more formats :)
