### ISSUE TITLE
arj when changing a computer

### ISSUE THREAD

**Issue by lka1976** [adoconnection/SevenZipExtractor#11]
I transferred the program to another computer, SevenZipExtractor stopped opening arj archives (does not see files in them)

```
SevenZipExtractor.ArchiveFile szip = new SevenZipExtractor.ArchiveFile(localDirectory + fileName);
 foreach  (Entry e in szip.Entries)   {....}

```no entry in szip.Entries
but on an old computer everything works

**Comment by adoconnection** [comment]
You are using this nuget package v1.0.7 right?
First thing I would check is seven zip binaries. Make sure 7z-x64.dll and 7z-x86.dll are near your executable.

**Comment by lka1976** [comment]
really was not dll
but the problem remained ...
compiled on 1 computer program is now working on any.
on 2 computers after compilation there is an exception
`System.AccessViolationException: "Attempting to read or write to protected memory .This often indicates that other memory is corrupt."`

```
 private void Do1Arj(string fileName)
        {
        
            string localDirectory = Path.GetDirectoryName(Application.ExecutablePath) + "\\" + "Temp\\";            
            SevenZipExtractor.ArchiveFile szip = new SevenZipExtractor.ArchiveFile(localDirectory + fileName);
            foreach  (Entry e in szip.Entries) // an exception occurs here 
            {
                posilka = e.FileName;
                if (posilka.Substring(0, 3) == "KWT") continue;
                AddRec();
            }
            szip.Dispose();
        }



```

**Comment by adoconnection** [comment]
@lka1976 can you please try latest SevenZipExtractor v1.0.10?

**Comment by lka1976** [comment]
Good afternoon!
the installation of 1.0.10 with NUGET did not help.
I uninstalled the package, copied SevenZipExtractor.dll from the working version and made a link to it. The program worked ..
