### ISSUE TITLE
Extracting a file from a .deb file

### ISSUE THREAD

**Issue by dviljoen** [adoconnection/SevenZipExtractor#16]
I'm trying to extract a single file from a debian package.  I extract the top level and it has two tar.xz files (control.tar.xz and data.tar.xz).  The file I want is in data.tar.xz.  I can create a new ArchiveFile instance of it, but it has only one entry (I'm assuming its data.tar), but the entry has no filename.  This seems to prevent me from extracting it.

How do you either: 1) recursively extract everything in the .deb file, or 2) extract a nameless .tar file from within a tar.xz file?

**Comment by dviljoen** [comment]
By the way, I can extract everything I need using the command-line tool, or shell extensions.

**Comment by adoconnection** [comment]
Hi, not to make it silent here, probably noone have ever tried it

**Comment by adoconnection** [comment]
https://github.com/adoconnection/SevenZipExtractor/wiki/Extract-tar.gz,-tag.xz
