### ISSUE TITLE
Redistribute permissions

### ISSUE THREAD

**Issue by BobbyGR** [adoconnection/SevenZipExtractor#18]
Hello! I have a project AIOMiner (https://github.com/BobbyGR/AIOMiner) and I would like to use SevenZipExtractor as the primary extractor for items that are needed.   Let me know what is needed.  also great job on this!

**Comment by adoconnection** [comment]
SevenZipExtractor it under MIT licence
7z dlls are under GNU LGPL
basically you can do whatever you want :)

**Comment by BobbyGR** [comment]
Didn't see this until now.  Thanks, just making sure.  I'll make sure you are in the credits.  Thanks again
