### ISSUE TITLE
Extracted files are locked

### ISSUE THREAD

**Issue by Leminkainen** [adoconnection/SevenZipExtractor#2]
Extracted files are locked in my scenario: 
when extracting files one by one in foreach and trying to open them, access is denied.

The problem is in Entry.cs ( https://github.com/adoconnection/SevenZipExtractor/blob/master/SevenZipExtractor/Entry.cs )

```
public void Extract(string fileName)
        {
            this.Extract(File.Create(fileName));
        }
```

which has to be changed to something like below (or other disposal variant) to prevent the locking

```
public void Extract(string fileName)
        {
            using (FileStream fs = File.Create(fileName))
                Extract(fs);
        }
```
By the way, thanks for the great wrapper. Really enjoy using it! Спасибо! :)

**Comment by adoconnection** [comment]
It's been a long time :)

Thank you for report, fixed code and nuget package
