### ISSUE TITLE
Extract to stream when entry is in folder

### ISSUE THREAD

**Issue by Toxaris-NL** [adoconnection/SevenZipExtractor#23]
I try to extract an entry to a memorystream, but this fails if the entry is in a directory in the archive.

My code is this:

```
using (ArchiveFile archiveFile = new ArchiveFile(FilePath)) {
                PageCount = archiveFile.Entries.Count;

                MemoryStream memoryStream = new MemoryStream();
                archiveFile.Entries.OrderBy(x => x.FileName).First().Extract(memoryStream);

               Image = Image.FromStream(memoryStream);
            }
```

This code works fine when the entry is in the root of the archive. Is there a way to make this work without resorting to extracting to file?

**Comment by adoconnection** [comment]
Looks like a bug, thanks for repotring

**Comment by adoconnection** [comment]
Actual tests cover extracting entry from folder to memory stream.
I would like to lose this issue.
