### ISSUE TITLE
Minimal example doesn't work...

### ISSUE THREAD

**Issue by geneb** [adoconnection/SevenZipExtractor#25]
The sample code below does nothing but throw this exception:
System.InvalidCastException: 'Unable to cast object of type 'System.UInt32' to type 'System.UInt64'.'
.. where it attempts to display the number of files in the archive.  I installed version 1.0.12 via the NuGet PM in Visual Studio 2017.

```cs
using System;
using SevenZipExtractor;

namespace ConsoleApp1 {
    class Program {
        static void Main(string[] args) {
            using (ArchiveFile archiveFile = new ArchiveFile(@"G:\batch\ANSIMATE.ARJ")) {
                Console.WriteLine("There's {0} files in the archive.", archiveFile.Entries.Count);
            }
        }
    }
}
```

Suggestions?
tnx.

g.

**Comment by geneb** [comment]
I suspect this is due to the project being created as a console application for .Net Core 2.1 - it doesn't happen using .Net 4.7.1.  Sorry for the noise.

**Comment by geneb** [comment]
It actually appears to be related to ARJ files.
I stepped through the code in order to find the point where the exception was being triggered - in this case it's simply, "Specified cast is not valid".

I've been able to trace it as far as the routine starting at line #209 in ArchiveFile.cs:
     private T GetProperty<T>(uint fileIndex, ItemPropId name)
        {
            PropVariant propVariant = new PropVariant();
            this.archive.GetProperty(fileIndex, name, ref propVariant);
            **// exception is thrown in the line below**
            T result = propVariant.VarType != VarEnum.VT_EMPTY
                ? (T) propVariant.GetObject()
                : default(T);

            propVariant.Clear();

            return result;
        }

The caller of this is on line #171 of ArchiveFile.cs:
 ulong size = this.GetProperty<ulong>(fileIndex, ItemPropId.kpidSize);

The value of this.VarType going into GetObject() (line 78 in SevenZipInterface.cs) is VT_UI4.  That causes the switch to execute the 'default' branch:
return Marshal.GetObjectForNativeVariant(PropHandle.AddrOfPinnedObject());
At that point my C#-fu is exhausted and I'm unable to discover the root cause of the issue.

help!

g.
Here's the file that is causing the issue:
http://annex.retroarchive.org/cdrom/cotc-1/BATCH/ANSIMATE.ARJ

**Comment by adoconnection** [comment]
Hi, there is a pull request from @sudoudaisuke 
I have not yet merged (sorry for that)
https://github.com/adoconnection/SevenZipExtractor/pull/22/commits/b9a7b0d1750dab838bba5bb188894a6751189653

It solve exactly this problem.

**Comment by geneb** [comment]
It's nice to see the fix is so simple. :)  Any ETA on when you'll be able to do the merge?

tnx!

g.

**Comment by geneb** [comment]
I just tried that patch by hand and it /almost/ works.  Now it reaches line 180 in ArchiveFile.cs:
string method = this.GetProperty<string>(fileIndex, ItemPropId.kpidMethod);
This triggers the exception "Cannot Convert type 'byte' to 'string'".
The variable propVariant.VarType in the GetProperty method is set to VT_UI1 at this point.
is the Method property actually supposed to be a string?  I can't seem to find anything about it...

tnx.
g.

**Comment by geneb** [comment]
I could have sworn I updated this last week.  The issue happened again with a different variable and archive type, so I just commented out the section that assigned the Method value entirely so I could continue my work.

g.

**Comment by geneb** [comment]
Apparently the edit I did last week didn't take - nor did the comment I /just/ added seem to appear.  I'll try again.
I ran into the same type conversion issue with a different type and decided to just comment out the Method assignment entirely so I could continue my work.  At some point it should be investigated to see why on earth the 7Zip API seems to return different variable types for the same field type.  Even if the origin archiving method uses the Method value differently, it should be presented as a "universal" type to the application that's consuming the api call.

g.

**Comment by Miles8of9** [comment]
Hi, sorry to disturb you, feel free to delete this comment if it violates your rules. I've hit this bug with arj files today. I see this issue is open since several months. Any chances it will be fixed any time soon? I would really need it. I've looked around but didn't find any other libraries that can read and uncompress .arj files.
Thanks for your understanding and your help.

**Comment by adoconnection** [comment]
@Miles8of9 hi, thanks for reminding about this. I will fix this till weekend.

**Comment by copa017** [comment]
another reminder 😉

but anyways, I want to THANK YOU developers very much for your work!

**Comment by adoconnection** [comment]
- Initial problem with ANSIMATE.ARJ is covered by test, (it works for me)
- Cannot Convert type 'byte' to 'string' is known to be resolved

Closing for now. Please reopen if problem remains.
