### ISSUE TITLE
Very slowly on large 7z archives

### ISSUE THREAD

**Issue by Sublihim** [adoconnection/SevenZipExtractor#31]
I have an archive larger than 1Gb. The archive contains about 3500 files. The largest file in the archive is about 6 Gb.

I use:
```
using (ArchiveFile archiveFile = new ArchiveFile(@"Archive.7z"))
{
    foreach (Entry entry in archiveFile.Entries)
    {
        // extract to file
        entry.Extract(newFileName);
    }
}
```

In comparison with a regular 7z extractor, it works hundreds of slower

**Comment by adoconnection** [comment]
This should be investigated closely.
As you can see in Extract method of Entry class, there is no special C# logic there, just passing stream.
https://github.com/adoconnection/SevenZipExtractor/blob/master/SevenZipExtractor/Entry.cs

My guess it is something related to SevenZip

**Comment by nocelab** [comment]
I confirm this behaviour with 7z archive with solid block of 4GB... very very slow!
The same contents compressed with 7z archive without solid block is fast... hope this can help

**Comment by adoconnection** [comment]
@nocelab are you extracting all files or just several specific?

can you please try, if this extract work the same way or not for you?

```
using (ArchiveFile archiveFile = new ArchiveFile(@"Archive.ARJ"))
{
    archiveFile.Extract("Output"); // extract all
}
```

**Comment by nocelab** [comment]
Yes, it works!
This is result (extract all 7477 files):
- non solid archive (56.7MB):

   - method "archiveFile.Extract": 30"
   - method "foreach (Entry entry ...": 38"

- solid block (4GB) archive (42.7MB):
   - method "archiveFile.Extract": 28"
   - method "foreach (Entry entry ...": 3h46'07" 😱😱😱

**Comment by adoconnection** [comment]
thats because foreach starts seeking entry from beginning of archive every time when archiveFile.Extract commands 7Z to just extract everyting

@Sublihim I guess you have the same problem

**Comment by nocelab** [comment]
sorry but... is not possibile a compromise if I need extract several files without extract entire archive?

**Comment by adoconnection** [comment]
@nocelab no problem:
using (ArchiveFile archiveFile = new ArchiveFile(@"Archive.ARJ"))
{
    archiveFile.Extract( entry => {
           if (mySpecialFiles.Contains(entry.FileName))
           {
                  return Path.Combine(outputFolder, entry.FileName); // where to put this particular file
           }
           else
           {
                 return null; // null means skip and do not extract
           }
    });
}

have not tested this code, but should be fine, you can see its source code at 
https://github.com/adoconnection/SevenZipExtractor/blob/master/SevenZipExtractor/ArchiveFile.cs

**Comment by nocelab** [comment]
Excellent... it works very well!!!
Please add it into README.md, it's important for not C# experts (like me!!!).
Thanks!

**Comment by adoconnection** [comment]
ok :)

**Comment by adoconnection** [comment]
wiki for future visitors: https://github.com/adoconnection/SevenZipExtractor/wiki/Extracting-from-solid-archives
