### ISSUE TITLE
Reliance on "C:\Program Files\7-Zip"

### ISSUE THREAD

**Issue by ceddlyburge** [adoconnection/SevenZipExtractor#32]
Hi there

We have just started using this, and it appears to be the case that it relies upon 7-Zip being available at "C:\Program Files\7-Zip".

Our deployed app wasn't working, and this was the way we found to fix it. Copying the files in to the same directory as our executable didn't work, and neither did installing 7-zip in to a different location.

Cheers

Cedd

**Comment by adoconnection** [comment]
Rather late reply.

All logic is located in InitializeAndValidateLibrary
https://github.com/adoconnection/SevenZipExtractor/blob/master/SevenZipExtractor/ArchiveFile.cs

First we try to find binaries in working folder, then in programm files.
Make sure you have SevenZip binaries on any of those paths.

**Comment by ceddlyburge** [comment]
Thanks! That code does look like it works, but I'm sure it didn't for us. Copying the files in to the same directory as the app seemed like the most obvious solution, so this is what we did first. Maybe we had the wrong dlls or something.
