### ISSUE TITLE
DateTime of compressed files are not restored when extracting

### ISSUE THREAD

**Issue by roy-van-de-korput** [adoconnection/SevenZipExtractor#34]
When extracting (file by file or whole archive directly), the file stamps of the entries are not updated to the original time in the archive. Every file will have it's last write time set to extracted time.

**Comment by adoconnection** [comment]
Should it be default behavior? 
as I can see in ArchiveFile.Extract and IInArchive.Extract its not now

**Comment by roy-van-de-korput** [comment]
Yes, default behavior. If I use other libraries in c# they restore the datetime. Also the case for GUI tools like 7zip or winrar. They also restore the datetime
