### ISSUE TITLE
Dll downloaded from nuget doesn't extract LZH file

### ISSUE THREAD

**Issue by MisiekPushUpek** [adoconnection/SevenZipExtractor#35]
When using dll from nuget package in version 1.0.12 extraction from lzh file doesn't work (0 entries and Exception).
When I get a dll from repository (exemple project) everything works perfect.
Please update nuget version of library.

**Comment by adoconnection** [comment]
Hi, done

https://www.nuget.org/packages/SevenZipExtractor/1.0.13

**Comment by adoconnection** [comment]
Added LZH unit test
