### ISSUE TITLE
Versions 1.0.10 to 1.0.14 doesn't work

### ISSUE THREAD

**Issue by mefmund** [adoconnection/SevenZipExtractor#37]
I install latest version SevenZipExtractor using nuget and I was trying the example code, but i have error 

> "The type or namespace name 'SevenZipExtractor' could not be found (are you missing a using directive or an assembly reference?)
I checked few more versions and problem diapers when i change version to 1.0.09

I'm using .net core 3.1

**Comment by adoconnection** [comment]
Hi, I think it is some sort of nuget compilation issue. 
It will not work if installed as nuget package, however if I download sources and reference SevenZipExtractor as a project - it works.

thanks for reporting!

**Comment by WojciechNagorski** [comment]
I fixed this problem in PR #38

**Comment by mefmund** [comment]
Confirmed. Version 1.0.15 is working.
