### ISSUE TITLE
MemoryStream's position is at the end

### ISSUE THREAD

**Issue by tonyp7** [adoconnection/SevenZipExtractor#42]
Not really a bug per say, but if you do:

```csharp
MemoryStream memoryStream = new MemoryStream();
Entry entry.Extract(memoryStream);
```

Then you cannot do memoryStream.Read; simply because the position of the stream is at the end. So now you have to do:

```csharp
MemoryStream memoryStream = new MemoryStream();
Entry entry.Extract(memoryStream);
memoryStream.Position = 0;
```
Before you can use the stream. I got bitten by this. It's not a bug but it's very counter intuitive and goes against typical designs we see elsewhere.

**Comment by adoconnection** [comment]
There is a small chance someone would extract to ResponseStream of web server where position change is not possible an will introduce hidden behavior.

I have exactly opposite experiece: every time I work with MemoryStream I need to keep an eye on its position, whether its set to 0 or not :)

**Comment by tonyp7** [comment]
OK -- I trust your judgement on this. Thank you for making this awesome lib available to us!

**Comment by adoconnection** [comment]
@tonyp7 thanks for kind words
