### ISSUE TITLE
Update 7z.dll to latest (v19.x)

### ISSUE THREAD

**Issue by duckheadsoftware** [adoconnection/SevenZipExtractor#48]
I noticed the 7z.dll version used in the Nuget package is 18.5, can this be updated to 19.x ?

**Comment by adoconnection** [comment]
yep, need to push new nuget version

**Comment by jorensanbar** [comment]
> yep, need to push new nuget version

Nuget Still on 18.5 version (2021-10-31)

**Comment by adoconnection** [comment]
done
