### ISSUE TITLE
Zip files over 4 gig.

### ISSUE THREAD

**Issue by fdameron** [adoconnection/SevenZipExtractor#49]
Working with zip files containing image files. When the files are larger than 4 gigs, the files up to 4 gig extract just fine, but all other files after that are 0 or 1 byte. I can extract them just fine with 7-zip. Looking at the archive, every file up to the 4 gig mark show characteristics NTFS, all files after that show characteristics Zip64 NTFS. I've tried extract all files, extract files one at a time, extract one at a time to stream. Thanks for any help on this issue.

**Comment by adoconnection** [comment]
Hi, I had this problem before but have no idea how to fix it :( Luckily it was a zip file so i switched to IconicZip for that particular case.

**Comment by fdameron** [comment]
We switched from ioniczip due to zip64 exceptions. Guess I'll try the 7-zip console lib. Thanks anyway.

**Comment by adoconnection** [comment]
fixed in 1.0.17!
