### ISSUE TITLE
Is there a thread-safe way to extract files?

### ISSUE THREAD

**Issue by makoshichi** [adoconnection/SevenZipExtractor#52]
Hi there!
I'm working on a library where I sometimes I will need to extract files in a new thread so it won't stall other things, but the following doesn't work:

        Task.Factory.StartNew(() =>
        {
            archiveFiles.ToList().ForEach(entry =>
            {
                var validPath = Path.Combine(destinationPath, targetFolder);
                Directory.CreateDirectory(validPath);

                using (MemoryStream ms = new MemoryStream())
                {
                    entry.Extract(ms); //throws exception
                    FileStream fs = new FileStream(Path.Combine(validPath, entry.FileName), FileMode.Create);
                    ms.WriteTo(fs);
                    fs.Close();
                }
            });
        });

The full exception is:

>System.Runtime.InteropServices.InvalidComObjectException: 'COM object that has been separated from its underlying RCW cannot be used.

I've searched that error around and it is said to be typical for operations that are not thread-safe. Is there a workaround or any plans to allow to perform this safely in the future?

**Comment by adoconnection** [comment]
Some late reply for enyone stuck on this.
its because archiveFiles is defined in outer thread.
