### ISSUE TITLE
I am unable to extract an .exe (7z self extracting archive) using SevenZipExtractor

### ISSUE THREAD

**Issue by Vazgi** [adoconnection/SevenZipExtractor#57]
```
 var file = @"C:\Users\PC\Desktop\SelfExtractFile.exe";
 var destination = @"C:\Users\PC\Desktop\";

 using ( ArchiveFile archiveFile = new ArchiveFile(file))
 {
   archiveFile.Extract(destination, true);
 }
```
I get: : 'Object reference not set to an instance of an object.' archive and entries are null.

The library says it supports .exe.

Any idea how to fix this?
This is the command for creating the file:
`7z a -sfx7z.sfx "SelfExtractFile.exe"  "C:\Users\PC\Desktop\*.*" -mmt -r`

**Comment by fgimian** [comment]
I'm not the maintainer of this great library, but I suspect the problem you're facing is due to the fact that the library is guessing your archive is a PE archive.  Try open it like this:

```c#
using (ArchiveFile archive = new ArchiveFile (File.OpenRead(file), format: SevenZipFormat.SevenZip))
...
```

Hope this help
Fotis

**Comment by Vazgi** [comment]
I have used another lib.
