### ISSUE TITLE
How to chanage unzipped file folder?

### ISSUE THREAD

**Issue by zydjohnHotmail** [adoconnection/SevenZipExtractor#58]
Hello:
I usually download a number of zipped files with multiple files inside, and default download drive is not big enough to hold many big files.
Therefore, I want to use the repo to unzip all the downloaded zip files to another drive.
But I can't figure out how to change the path for unzipped files.
Please advise.
I am using SevenZipExtractor 1.0.17 on Windows 10 (Version 21H2).
Thanks,

**Comment by jorensanbar** [comment]
```
using (SevenZipExtractor.ArchiveFile _archiveFile = new SevenZipExtractor.ArchiveFile(inFilePath))
{
_archiveFile.Extract(destinationPath, true);
}
```
