### ISSUE TITLE
Is it possible to extract files from single zip file in parallel

### ISSUE THREAD

**Issue by pia29** [adoconnection/SevenZipExtractor#61]
For me, for files with size > 1MB, in parallel execution 
meta data is not getting copied for dll files

**Comment by adoconnection** [comment]
nust to be sure, whats your bottleneck, CPU or Disk?

**Comment by pia29** [comment]
actually i am extracting wim file which has lakhs of files, this is done in azure function. Azure function has timeout currently for half hour, this extraction is taking more than 1 hour, so that's why, i was trying to do it in parallel.


My current code:
 using (ArchiveFile archiveFile = new ArchiveFile(wimCompleteFilePath))
            {
                var data = archiveFile.Entries;
                var folderFileGroup = data.GroupBy(x => x.IsFolder);
                var folders = folderFileGroup.Where(x => x.Key == true).Select(y => y.ToList()).FirstOrDefault();

                if (folders != null)
                {
                    folders.AsParallel().WithDegreeOfParallelism(batchSize).ForAll(folder =>
                    {
                        var path = Path.Combine(localDirCompleteFilePath, folder.FileName);
                        if (!this._fileSystem.Directory.Exists(path))
                        {
                            this._fileSystem.Directory.CreateDirectory(path);
                        }
                    });
                }

                var files = folderFileGroup.Where(x => x.Key == false).Select(y => y.ToList()).FirstOrDefault();

                if (files != null)
                {
                    files.AsParallel().WithDegreeOfParallelism(batchSize).ForAll(async file =>
                    {
                        var filePath = Path.Combine(localDirCompleteFilePath, file.FileName);
                        file.Extract(filePath);
                    });
                }

**Comment by adoconnection** [comment]
most likely you are facing this issue: https://github.com/adoconnection/SevenZipExtractor/wiki/Extracting-from-solid-archives

does this work in azure functuins?
```
using (ArchiveFile archiveFile = new ArchiveFile(@"Archive.ARJ"))
{
    archiveFile.Extract(localDirCompleteFilePath); // extract all
}
```

**Comment by pia29** [comment]
This is working but problem with this is 
1. Takes a lot of time
2. Timestamps get modified.

thank you for the suggestion and quick response.
