### ISSUE TITLE
Exception : The string was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by AtlantisDe** [adoconnection/SevenZipExtractor#68]
### The string was not recognized as a valid DateTime
- Unzip the package, abnormal! On some computers.
- amd64.7z `my files are normal`
- `OS` -- ``Windows 10 Enterprise LTSC ``
```c#
 try
  {

      using (SevenZipExtractor.ArchiveFile archiveFile = new SevenZipExtractor.ArchiveFile(sourceFileName))
      {
          archiveFile.Extract(destinationDirectory, true); // extract all
      }

  }
  catch (Exception ex)
  { 
      System.Windows.Forms.MessageBox.Show(ex.Message, "Message", MessageBoxButtons.OK, MessageBoxIcon.Warning);
      System.Environment.Exit(0);

  }
  finally { }
```

**Comment by adoconnection** [comment]
Hi, I need more details to proceed, can you share archive and details to reproduce?

I suggest you take source code and run it against your archive so you will see exact place and data of this exception

**Comment by AtlantisDe** [comment]
> Hi, I need more details to proceed, can you share archive and details to reproduce?
> 
> I suggest you take source code and run it against your archive so you will see exact place and data of this exception

It is a bit difficult to reproduce, this is an exception that occurs on the client machine
I'll see for myself

**Comment by AtlantisDe** [comment]
> Hi, I need more details to proceed, can you share archive and details to reproduce?
> 
> I suggest you take source code and run it against your archive so you will see exact place and data of this exception

### Exception picture information
- [https://github.com/AtlantisDe/GithubHelper/tree/main/Github/Images/202305](https://github.com/AtlantisDe/GithubHelper/tree/main/Github/Images/202305)
- [SevenZipExtractor_Exception_001.png](https://raw.githubusercontent.com/AtlantisDe/GithubHelper/main/Github/Images/202305/SevenZipExtractor_Exception_001.png)
- [SevenZipExtractor_Exception_002.png](https://raw.githubusercontent.com/AtlantisDe/GithubHelper/main/Github/Images/202305/SevenZipExtractor_Exception_002.png)
- [SevenZipExtractor_Exception_002.png](https://raw.githubusercontent.com/AtlantisDe/GithubHelper/main/Github/Images/202305/SevenZipExtractor_Exception_002.png)

```
Please check it out.
```

**Comment by adoconnection** [comment]
Thanks! One more thing, what was the value?

![image](https://user-images.githubusercontent.com/499855/236615698-c4d91ac0-c72f-45f4-b1f5-1ba2f6d20f9e.png)

**Comment by AtlantisDe** [comment]
> * Windows 10 Enterprise LTSC

- [SevenZipExtractor_Exception_004.png](https://raw.githubusercontent.com/AtlantisDe/GithubHelper/main/Github/Images/202305/SevenZipExtractor_Exception_004.png)
- Cause this problem, it should be, time string, conversion problem.

**Comment by adoconnection** [comment]
Thanks! this helps a lot!
