### ISSUE TITLE
nuget package is constrained to net45

### ISSUE THREAD

**Issue by Guy--L** [adoconnection/SevenZipExtractor#7]
Package SevenZipExtractor 1.0.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package SevenZipExtractor 1.0.5 supports: net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETCoreApp,Version=v1.0.
Package restore failed. Rolling back package changes for 'needyproject'.
Time Elapsed: 00:00:02.8476243
========== Finished ==========

**Comment by adoconnection** [comment]
Hi, not sure if this approach is working with Core as this library is only a wrapper with marchaling and WinApi.

However my quick research tells Core has all the marchaling functionality. 
Do you run your core app under windows?

**Comment by Quinity** [comment]
I didn't get SevenZipExtractor to work with .NET Core. 
I'm using the .NET Core 2.0 preview, where you can reference .NET Framework libraries, since they implement the same .NET Standard version (here: 2.0).
Unfortunately, calling `ArchiveFile(MemoryStream, Format)` either leads to `AccessViolationException` or `ExecutionEngineException`, both which are low level errors.

**Comment by adoconnection** [comment]
Maybe we can translate 7z to c# and solve this pain one and for all?

**Comment by adoconnection** [comment]
@Guy--L can you please test latest v1.0.10 nuget package?

**Comment by Kaon68** [comment]
I've tested v1.0.10 with a .NET Standard 1.4 project. 
No warn about compatibility of this package with .NET Standard

No .Net Standard dll in package to reference, 7z.dll are added but not SevenZipExtractor.

**Comment by adoconnection** [comment]
@Kaon68 do you know how to fix it?

**Comment by Kaon68** [comment]
I don't know how nuget package are done, but you need to include a version of your dll(s) for every .net framework subset you want to be compatible. I advise you to turn to .Net Standard as it is multi platform.

For nuget package config, you'll have to search ^^

PS : for now, I looked at another 7z package which is .net standard compatible.

**Comment by dalbani** [comment]
@Kaon68: did you evenutally find such .NET Standard compatible package?

**Comment by WojciechNagorski** [comment]
I think that this issue should be fixed in PR #38.
