### ISSUE TITLE
How i can set a password to extract password protected 7z file? 

### ISSUE THREAD

**Issue by SalmaBegumJSR** [adoconnection/SevenZipExtractor#77]
as the title says.. how can i extract files form a password protected 7z file? please?

i don't see any option to set the password.. to extract.. 

thanks in advance.. 

best regards

**Comment by adoconnection** [comment]
Hi, it was never implemented, alas

**Comment by adoconnection** [comment]
As SevenZipExtractor is simply a wrapper, there must be quite straightforward way to add password support simply passing password string at the right moment, need to find where

**Comment by SalmaBegumJSR** [comment]
> As SevenZipExtractor is simply a wrapper, there must be quite straightforward way to add password support simply passing password string at the right moment, need to find where

sir, yes though i know it's a wrapper only.. but if i knew where and how to pass the password, then i wouldn't have bother you by this post/messages. 

in other words, you are way too expert than me, in your case you may need few minutes to hardly an hour where in my case it can take few days to months.

so, i will be more than grateful if you can kindly show me how to do that (update/add codes to which code file)..

for your referee following library/project can handle the password, but issue is, it can't handle the solid archive to extract from.

https://github.com/squid-box/SevenZipSharp

thanks in advance for your upcoming response/help/support

best regards

**Comment by SalmaBegumJSR** [comment]
any help please? 

please don't mind and don't take it otherwise.. but i am happy to buy you a coffee.. if that works.. 

thanks in advance

best regards

**Comment by adoconnection** [comment]
Hi, it turned out its really a matter of few minutes to add password support, preparing new version

**Comment by SalmaBegumJSR** [comment]
> Hi, it turned out its really a matter of few minutes to add password support, preparing new version

that is so kind of you.. will be waiting for the new version...

**Comment by SalmaBegumJSR** [comment]
any news for me? @adoconnection

**Comment by adoconnection** [comment]
New version finally here:
https://www.nuget.org/packages/SevenZipExtractor/1.0.19

```cs
using (ArchiveFile archiveFile = new ArchiveFile(@"Archive.arj"))
{
    archiveFile.Extract("Output", password: "mySecret");
}
```
