### ISSUE TITLE
Can't instantiate SevenZipExtractor object using file name with no extension

### ISSUE THREAD

**Issue by BrewmeisterP** [adoconnection/SevenZipExtractor#8]
Trying to call this...
     Public Sub New(archiveFullName As String)
with this...
     Dim SevenZipEx As SevenZip.SevenZipExtractor = Nothing
     SevenZipEx = New SevenZip.SevenZipExtractor("C:\Temp\test")
Results in this exception...
     		startIndex cannot be larger than length of string." & vbCrLf & "Parameter name: startInde"

**Comment by adoconnection** [comment]
Hi, you write in wrong github repo :)
ZevenZip (https://sevenzipsharp.codeplex.com/) is no longer supported.

this is another project to fix this.
do:
Install-Package SevenZipExtractor 

using (ArchiveFile archiveFile = new ArchiveFile(@"yourFilePath", SevenZipFormat.Rar))
{
    archiveFile.Extract("Output"); // extract all
}

**Comment by BrewmeisterP** [comment]
Thanks!
